name: Fetch PubMed Data

on:
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday at midnight UTC
  push:
    branches: [main]      # On push to main
  workflow_dispatch:      # Manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run fetch script
        run: |
          chmod +x create_pubs.sh
          ./create_pubs.sh

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update PubMed data [skip ci]" || echo "No changes to commit"
          git push
